### PR TITLE
A lot of things xD

### PR DESCRIPTION
**Pull request by alpheratz0**
## Modificaciones (supongo que hablas espanol)
- Puse todo en un archivo unico (separe todo en funciones y volvi a escribi bastantes cosas)
- Ahora acepta opciones (por ejemplo para mostar en espanol: `tree.sh --language es`)
- Cree carpeta con lenguajes (los que ya estaban, espanol e ingles)
- Ahora es mas facil agregar otros lenguajes
- Le agregue un gif al readme para que se pueda ver el resultado

Espero lo puedas mergear, saludos!!!

### CODE REVIEW

**Comment by SuperQ** [comment]
Nice rewrite. Maybe you want to pick my translation method in #14 in order to avoid having to spit the translations out.

**Comment by alpheratz0** [comment]
@SuperQ

I'm not the owner of this repo and as you may see pull requests arent being reviewed by his owner :(

> Nice rewrite. Maybe you want to pick my translation method in #14 in order to avoid having to spit the translations out.

I prefer to keep translation messages in separate files, just imagine if in some months support for 20 languages is added, that would be 200+ lines of code in the tree.sh file, that sounds messy, in the other hand if you only need a few languages supported I think it wouldnt matter at all to move all translations to the tree.sh file.

Keep up the good work!

**Comment by SuperQ** [comment]
The problem with splitting it out is you need to download all the files, rather than just the one script. It also makes it messy to use because if you wanted to package it for deb/rpm, it now requires modifications to support putting the translations in a different location from the script (/usr/bin/ vs /usr/lib/).

**Comment by alpheratz0** [comment]
> The problem with splitting it out is you need to download all the files, rather than just the one script. It also makes it messy to use because if you wanted to package it for deb/rpm, it now requires modifications to support putting the translations in a different location from the script (/usr/bin/ vs /usr/lib/).

That's a good point, done! 
https://github.com/alpheratz0/tree.sh

**Pull request closed without merging**
